service: aws-node-user-manager

frameworkVersion: '2'

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256
  httpApi:
    cors: true
  environment:
    DB: ${self:custom.secrets.DB}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASS: ${self:custom.secrets.DB_PASS}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
    SLS_DEBUG: '*'

functions:
  createUser:
    handler: src/routes/handler.createUser
    description: To create a new user
    timeout: 10
    events:
      - httpApi: 'POST /user'
  
  listUsers:
    handler: src/routes/handler.listUsers
    description: To list all the users
    timeout: 10
    events:
      - httpApi: 'GET /user'
  
  updateUser:
    handler: src/routes/handler.updateUser
    description: To update one users
    timeout: 10
    events:
      - httpApi: 'PUT /user/{id}'

  deleteUser:
    handler: src/routes/handler.deleteUser
    description: To delete one user
    timeout: 10
    events:
      - httpApi: 'DELETE /user/{id}'

plugins:
  - serverless-offline