service: aws-node-user-manager

frameworkVersion: '2'

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: sa-east-1
  memorySize: 256
  httpApi:
    cors: true
  environment:
    SLS_DEBUG: '*'
    DB: ${self:custom.secrets.DB}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASS: ${self:custom.secrets.DB_PASS}
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}

functions:
  verify-token:
    handler: src/app/auth/VerifyToken.auth

  createSuperUser:
    handler: src/app/superUsers/handler.createSuperUser
    description: To create a new super user
    timeout: 10
    events:
      - httpApi: 'POST /superUser'
  
  createSession:
    handler: src/app/superUsers/handler.createSession
    description: To start a new session
    timeout: 10
    events:
      - httpApi: 'POST /session'

  createUser:
    handler: src/app/users/handler.createUser
    description: To create a new user
    timeout: 10
    events:
      - httpApi: 
          method: post 
          path: /user
          # authorizer: 
          #   name: verify-token
          #   identitySource: method.request.header.Authorization
  
  listUsers:
    handler: src/app/users/handler.listUsers
    description: To list all the users
    timeout: 10
    events:
      - httpApi: 
          method: GET
          path: /user
          authorizer: 
            name: verify-token
            identitySource: method.request.header.Authorization
  
  updateUser:
    handler: src/users/handler.updateUser
    description: To update one users
    timeout: 10
    events:
      - httpApi: 'PUT /user/{id}'

  deleteUser:
    handler: src/users/handler.deleteUser
    description: To delete one user
    timeout: 10
    events:
      - httpApi: 'DELETE /user/{id}'

plugins:
  - serverless-offline